spring:
  flyway:
    locations: classpath:db/migration
    schemas: bot
    enabled: true
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    database: postgresql
  datasource:
#    url: jdbc:postgresql://${RDS_HOSTNAME:localhost}:${RDS_PORT:5432}/${RDS_DB_NAME:postgres}?currentSchema=bot
    url: jdbc:postgresql://${RDS_HOSTNAME:45.8.251.166}:${RDS_PORT:5432}/${RDS_DB_NAME:postgres}?currentSchema=bot
#    url: jdbc:postgresql://${RDS_HOSTNAME:host.docker.internal:${RDS_PORT:5432}/${RDS_DB_NAME:bot}?currentSchema=bot
    username: ${RDS_USERNAME:postgres}
    password: ${RDS_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    pool-size: 30
  main:
    allow-circular-references: true

bot:
  name: TradeHelperBot
  token: 6967437002:AAEZds47kCq2KtReJ6gC_Sh-GmMGr8LDId4
  owner: 1

management:
  endpoints.web.exposure.include: 'prometheus, health'
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true

server:
  port: 8080

list.symbol: NOT,BTC,AAVE,BNB,OP,ARB,WLD,SOL,INJ,LINK,APT

key: ${KEY:KEY}
secret: ${SECRET:SECRET}

logging:
  level:
#    root: WARN
    org.springframework: info
    org.apache: info
    com.zaxxer: info
    org.hibernate.SQL: INFO
    o.h.internal.util: info
    o.h.internal.util.EntityPrinter: info
    com.trade.bot.handler.OkxTradeHandler: DEBUG
    org.hibernate.engine.jdbc: info
    org.hibernate: ERROR
    com.bybit.api.client.service: ERROR


accounts: ${ACCOUNTS:{}}

hour: ${HOUR}
