package com.logicaScoolBot.entity;

public enum Course {
    OLIP,
    PYTHON,
    ADMIN_DUBNA,
    ADMIN_MOSKOW,
    ADMIN_VOSKRESENSK,
    ADMIN_RAMENSKOE,
    ADMIN_TEST,
    TEACHER_DUBNA,
    TEACHER_MOSKOW,
    TEACHER_VOSKRESENSK,
    TEACHER_RAMENSKOE
}
