ALTER TABLE bot.bar ALTER COLUMN vol_buy  TYPE DOUBLE PRECISION USING vol_buy::DOUBLE PRECISION;
ALTER TABLE bot.bar ALTER COLUMN vol_sell TYPE DOUBLE PRECISION USING vol_sell::DOUBLE PRECISION;;
ALTER TABLE bot.bar ALTER COLUMN "open" TYPE  DOUBLE PRECISION USING "open"::DOUBLE PRECISION;
ALTER TABLE bot.bar ALTER COLUMN "close" TYPE DOUBLE PRECISION USING "close"::DOUBLE PRECISION;
ALTER TABLE bot.bar ALTER COLUMN high TYPE    DOUBLE PRECISION USING high::DOUBLE PRECISION;
ALTER TABLE bot.bar ALTER COLUMN low TYPE     DOUBLE PRECISION USING low::DOUBLE PRECISION;
ALTER TABLE bot.bar ADD COLUMN   vol           DOUBLE PRECISION;
ALTER TABLE bot.bar ADD COLUMN   interval      INT;

create index if not exists idx_create_date_symbol on bot.bar (symbol, create_date, interval);
